// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class UploadStartResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UploadStartResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUploadStartResponse(bb:flatbuffers.ByteBuffer, obj?:UploadStartResponse):UploadStartResponse {
  return (obj || new UploadStartResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUploadStartResponse(bb:flatbuffers.ByteBuffer, obj?:UploadStartResponse):UploadStartResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UploadStartResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ok():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

uploadId():string|null
uploadId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
uploadId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

error():string|null
error(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
error(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startUploadStartResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addOk(builder:flatbuffers.Builder, ok:boolean) {
  builder.addFieldInt8(0, +ok, +false);
}

static addUploadId(builder:flatbuffers.Builder, uploadIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, uploadIdOffset, 0);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, errorOffset, 0);
}

static endUploadStartResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUploadStartResponse(builder:flatbuffers.Builder, ok:boolean, uploadIdOffset:flatbuffers.Offset, errorOffset:flatbuffers.Offset):flatbuffers.Offset {
  UploadStartResponse.startUploadStartResponse(builder);
  UploadStartResponse.addOk(builder, ok);
  UploadStartResponse.addUploadId(builder, uploadIdOffset);
  UploadStartResponse.addError(builder, errorOffset);
  return UploadStartResponse.endUploadStartResponse(builder);
}
}
