// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChatItem struct {
	_tab flatbuffers.Table
}

func GetRootAsChatItem(buf []byte, offset flatbuffers.UOffsetT) *ChatItem {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChatItem{}
	x.Init(buf, n+offset)
	return x
}

func FinishChatItemBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChatItem(buf []byte, offset flatbuffers.UOffsetT) *ChatItem {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChatItem{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChatItemBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChatItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChatItem) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChatItem) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChatItem) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ChatItem) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatItem) Avatar() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatItem) Type() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChatItem) MutateType(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *ChatItem) LastMessage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChatItem) LastMessageTime() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChatItem) MutateLastMessageTime(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *ChatItem) LastSenderId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChatItem) MutateLastSenderId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *ChatItem) LastMessageStatus() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChatItem) MutateLastMessageStatus(n uint16) bool {
	return rcv._tab.MutateUint16Slot(18, n)
}

func (rcv *ChatItem) Unread() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChatItem) MutateUnread(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

func (rcv *ChatItem) Pinned() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ChatItem) MutatePinned(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func ChatItemStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func ChatItemAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(0, id, 0)
}
func ChatItemAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func ChatItemAddAvatar(builder *flatbuffers.Builder, avatar flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(avatar), 0)
}
func ChatItemAddType(builder *flatbuffers.Builder, type_ byte) {
	builder.PrependByteSlot(3, type_, 0)
}
func ChatItemAddLastMessage(builder *flatbuffers.Builder, lastMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(lastMessage), 0)
}
func ChatItemAddLastMessageTime(builder *flatbuffers.Builder, lastMessageTime uint32) {
	builder.PrependUint32Slot(5, lastMessageTime, 0)
}
func ChatItemAddLastSenderId(builder *flatbuffers.Builder, lastSenderId uint64) {
	builder.PrependUint64Slot(6, lastSenderId, 0)
}
func ChatItemAddLastMessageStatus(builder *flatbuffers.Builder, lastMessageStatus uint16) {
	builder.PrependUint16Slot(7, lastMessageStatus, 0)
}
func ChatItemAddUnread(builder *flatbuffers.Builder, unread uint32) {
	builder.PrependUint32Slot(8, unread, 0)
}
func ChatItemAddPinned(builder *flatbuffers.Builder, pinned bool) {
	builder.PrependBoolSlot(9, pinned, false)
}
func ChatItemEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
