// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreatePrivateChatRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCreatePrivateChatRequest(buf []byte, offset flatbuffers.UOffsetT) *CreatePrivateChatRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreatePrivateChatRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishCreatePrivateChatRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCreatePrivateChatRequest(buf []byte, offset flatbuffers.UOffsetT) *CreatePrivateChatRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CreatePrivateChatRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCreatePrivateChatRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CreatePrivateChatRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreatePrivateChatRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CreatePrivateChatRequest) ContactId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CreatePrivateChatRequest) MutateContactId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func CreatePrivateChatRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CreatePrivateChatRequestAddContactId(builder *flatbuffers.Builder, contactId uint64) {
	builder.PrependUint64Slot(0, contactId, 0)
}
func CreatePrivateChatRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
