// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeleteMessageRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteMessageRequest(buf []byte, offset flatbuffers.UOffsetT) *DeleteMessageRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteMessageRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeleteMessageRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeleteMessageRequest(buf []byte, offset flatbuffers.UOffsetT) *DeleteMessageRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeleteMessageRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeleteMessageRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeleteMessageRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteMessageRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteMessageRequest) MessageId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeleteMessageRequest) MutateMessageId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *DeleteMessageRequest) ChatId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeleteMessageRequest) MutateChatId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func DeleteMessageRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DeleteMessageRequestAddMessageId(builder *flatbuffers.Builder, messageId uint64) {
	builder.PrependUint64Slot(0, messageId, 0)
}
func DeleteMessageRequestAddChatId(builder *flatbuffers.Builder, chatId uint64) {
	builder.PrependUint64Slot(1, chatId, 0)
}
func DeleteMessageRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
