// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EditMessageRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsEditMessageRequest(buf []byte, offset flatbuffers.UOffsetT) *EditMessageRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EditMessageRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishEditMessageRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEditMessageRequest(buf []byte, offset flatbuffers.UOffsetT) *EditMessageRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EditMessageRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEditMessageRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EditMessageRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EditMessageRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EditMessageRequest) MessageId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EditMessageRequest) MutateMessageId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *EditMessageRequest) ChatId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EditMessageRequest) MutateChatId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *EditMessageRequest) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EditMessageRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func EditMessageRequestAddMessageId(builder *flatbuffers.Builder, messageId uint64) {
	builder.PrependUint64Slot(0, messageId, 0)
}
func EditMessageRequestAddChatId(builder *flatbuffers.Builder, chatId uint64) {
	builder.PrependUint64Slot(1, chatId, 0)
}
func EditMessageRequestAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(text), 0)
}
func EditMessageRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
