// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetMessagesRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetMessagesRequest(buf []byte, offset flatbuffers.UOffsetT) *GetMessagesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetMessagesRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetMessagesRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetMessagesRequest(buf []byte, offset flatbuffers.UOffsetT) *GetMessagesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetMessagesRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetMessagesRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetMessagesRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetMessagesRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetMessagesRequest) ChatId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetMessagesRequest) MutateChatId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *GetMessagesRequest) Limit() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetMessagesRequest) MutateLimit(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *GetMessagesRequest) Cursor() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GetMessagesRequest) MutateCursor(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func GetMessagesRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GetMessagesRequestAddChatId(builder *flatbuffers.Builder, chatId uint64) {
	builder.PrependUint64Slot(0, chatId, 0)
}
func GetMessagesRequestAddLimit(builder *flatbuffers.Builder, limit uint16) {
	builder.PrependUint16Slot(1, limit, 0)
}
func GetMessagesRequestAddCursor(builder *flatbuffers.Builder, cursor uint64) {
	builder.PrependUint64Slot(2, cursor, 0)
}
func GetMessagesRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
