// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessageStatusPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageStatusPayload(buf []byte, offset flatbuffers.UOffsetT) *MessageStatusPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageStatusPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageStatusPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageStatusPayload(buf []byte, offset flatbuffers.UOffsetT) *MessageStatusPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageStatusPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageStatusPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageStatusPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageStatusPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageStatusPayload) MessageId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageStatusPayload) MutateMessageId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *MessageStatusPayload) Status() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageStatusPayload) MutateStatus(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func MessageStatusPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MessageStatusPayloadAddMessageId(builder *flatbuffers.Builder, messageId uint64) {
	builder.PrependUint64Slot(0, messageId, 0)
}
func MessageStatusPayloadAddStatus(builder *flatbuffers.Builder, status uint16) {
	builder.PrependUint16Slot(1, status, 0)
}
func MessageStatusPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
