// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SendMessageResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSendMessageResponse(buf []byte, offset flatbuffers.UOffsetT) *SendMessageResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SendMessageResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSendMessageResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSendMessageResponse(buf []byte, offset flatbuffers.UOffsetT) *SendMessageResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SendMessageResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSendMessageResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SendMessageResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SendMessageResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SendMessageResponse) MessageId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SendMessageResponse) MutateMessageId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *SendMessageResponse) CreatedAt() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SendMessageResponse) MutateCreatedAt(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func SendMessageResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SendMessageResponseAddMessageId(builder *flatbuffers.Builder, messageId uint64) {
	builder.PrependUint64Slot(0, messageId, 0)
}
func SendMessageResponseAddCreatedAt(builder *flatbuffers.Builder, createdAt uint32) {
	builder.PrependUint32Slot(1, createdAt, 0)
}
func SendMessageResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
