// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Chat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SendMessageRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSendMessageRequest(buf []byte, offset flatbuffers.UOffsetT) *SendMessageRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SendMessageRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSendMessageRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSendMessageRequest(buf []byte, offset flatbuffers.UOffsetT) *SendMessageRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SendMessageRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSendMessageRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SendMessageRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SendMessageRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SendMessageRequest) ChatId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SendMessageRequest) MutateChatId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *SendMessageRequest) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SendMessageRequest) ContentType() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SendMessageRequest) MutateContentType(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *SendMessageRequest) ReplyToId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SendMessageRequest) MutateReplyToId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func SendMessageRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func SendMessageRequestAddChatId(builder *flatbuffers.Builder, chatId uint64) {
	builder.PrependUint64Slot(0, chatId, 0)
}
func SendMessageRequestAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(text), 0)
}
func SendMessageRequestAddContentType(builder *flatbuffers.Builder, contentType uint16) {
	builder.PrependUint16Slot(2, contentType, 0)
}
func SendMessageRequestAddReplyToId(builder *flatbuffers.Builder, replyToId uint64) {
	builder.PrependUint64Slot(3, replyToId, 0)
}
func SendMessageRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
