// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ChatItem {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatItem(bb:flatbuffers.ByteBuffer, obj?:ChatItem):ChatItem {
  return (obj || new ChatItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatItem(bb:flatbuffers.ByteBuffer, obj?:ChatItem):ChatItem {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

avatar():string|null
avatar(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
avatar(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

type():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

lastMessage():string|null
lastMessage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
lastMessage(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

lastMessageTime():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

lastSenderId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

lastMessageStatus():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

unread():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

pinned():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startChatItem(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addId(builder:flatbuffers.Builder, id:bigint) {
  builder.addFieldInt64(0, id, BigInt('0'));
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addAvatar(builder:flatbuffers.Builder, avatarOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, avatarOffset, 0);
}

static addType(builder:flatbuffers.Builder, type:number) {
  builder.addFieldInt8(3, type, 0);
}

static addLastMessage(builder:flatbuffers.Builder, lastMessageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, lastMessageOffset, 0);
}

static addLastMessageTime(builder:flatbuffers.Builder, lastMessageTime:number) {
  builder.addFieldInt32(5, lastMessageTime, 0);
}

static addLastSenderId(builder:flatbuffers.Builder, lastSenderId:bigint) {
  builder.addFieldInt64(6, lastSenderId, BigInt('0'));
}

static addLastMessageStatus(builder:flatbuffers.Builder, lastMessageStatus:number) {
  builder.addFieldInt16(7, lastMessageStatus, 0);
}

static addUnread(builder:flatbuffers.Builder, unread:number) {
  builder.addFieldInt32(8, unread, 0);
}

static addPinned(builder:flatbuffers.Builder, pinned:boolean) {
  builder.addFieldInt8(9, +pinned, +false);
}

static endChatItem(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChatItem(builder:flatbuffers.Builder, id:bigint, nameOffset:flatbuffers.Offset, avatarOffset:flatbuffers.Offset, type:number, lastMessageOffset:flatbuffers.Offset, lastMessageTime:number, lastSenderId:bigint, lastMessageStatus:number, unread:number, pinned:boolean):flatbuffers.Offset {
  ChatItem.startChatItem(builder);
  ChatItem.addId(builder, id);
  ChatItem.addName(builder, nameOffset);
  ChatItem.addAvatar(builder, avatarOffset);
  ChatItem.addType(builder, type);
  ChatItem.addLastMessage(builder, lastMessageOffset);
  ChatItem.addLastMessageTime(builder, lastMessageTime);
  ChatItem.addLastSenderId(builder, lastSenderId);
  ChatItem.addLastMessageStatus(builder, lastMessageStatus);
  ChatItem.addUnread(builder, unread);
  ChatItem.addPinned(builder, pinned);
  return ChatItem.endChatItem(builder);
}
}
