// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CreatePrivateChatResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CreatePrivateChatResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCreatePrivateChatResponse(bb:flatbuffers.ByteBuffer, obj?:CreatePrivateChatResponse):CreatePrivateChatResponse {
  return (obj || new CreatePrivateChatResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCreatePrivateChatResponse(bb:flatbuffers.ByteBuffer, obj?:CreatePrivateChatResponse):CreatePrivateChatResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CreatePrivateChatResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

chatId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startCreatePrivateChatResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addChatId(builder:flatbuffers.Builder, chatId:bigint) {
  builder.addFieldInt64(0, chatId, BigInt('0'));
}

static endCreatePrivateChatResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCreatePrivateChatResponse(builder:flatbuffers.Builder, chatId:bigint):flatbuffers.Offset {
  CreatePrivateChatResponse.startCreatePrivateChatResponse(builder);
  CreatePrivateChatResponse.addChatId(builder, chatId);
  return CreatePrivateChatResponse.endCreatePrivateChatResponse(builder);
}
}
