// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class MarkReadRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MarkReadRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMarkReadRequest(bb:flatbuffers.ByteBuffer, obj?:MarkReadRequest):MarkReadRequest {
  return (obj || new MarkReadRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMarkReadRequest(bb:flatbuffers.ByteBuffer, obj?:MarkReadRequest):MarkReadRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MarkReadRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

messageId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startMarkReadRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMessageId(builder:flatbuffers.Builder, messageId:bigint) {
  builder.addFieldInt64(0, messageId, BigInt('0'));
}

static endMarkReadRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMarkReadRequest(builder:flatbuffers.Builder, messageId:bigint):flatbuffers.Offset {
  MarkReadRequest.startMarkReadRequest(builder);
  MarkReadRequest.addMessageId(builder, messageId);
  return MarkReadRequest.endMarkReadRequest(builder);
}
}
