// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class MessageStatusPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MessageStatusPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMessageStatusPayload(bb:flatbuffers.ByteBuffer, obj?:MessageStatusPayload):MessageStatusPayload {
  return (obj || new MessageStatusPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMessageStatusPayload(bb:flatbuffers.ByteBuffer, obj?:MessageStatusPayload):MessageStatusPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MessageStatusPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

messageId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

status():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startMessageStatusPayload(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMessageId(builder:flatbuffers.Builder, messageId:bigint) {
  builder.addFieldInt64(0, messageId, BigInt('0'));
}

static addStatus(builder:flatbuffers.Builder, status:number) {
  builder.addFieldInt16(1, status, 0);
}

static endMessageStatusPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMessageStatusPayload(builder:flatbuffers.Builder, messageId:bigint, status:number):flatbuffers.Offset {
  MessageStatusPayload.startMessageStatusPayload(builder);
  MessageStatusPayload.addMessageId(builder, messageId);
  MessageStatusPayload.addStatus(builder, status);
  return MessageStatusPayload.endMessageStatusPayload(builder);
}
}
