// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class TypingPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TypingPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTypingPayload(bb:flatbuffers.ByteBuffer, obj?:TypingPayload):TypingPayload {
  return (obj || new TypingPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTypingPayload(bb:flatbuffers.ByteBuffer, obj?:TypingPayload):TypingPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TypingPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

chatId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

userId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startTypingPayload(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addChatId(builder:flatbuffers.Builder, chatId:bigint) {
  builder.addFieldInt64(0, chatId, BigInt('0'));
}

static addUserId(builder:flatbuffers.Builder, userId:bigint) {
  builder.addFieldInt64(1, userId, BigInt('0'));
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static endTypingPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTypingPayload(builder:flatbuffers.Builder, chatId:bigint, userId:bigint, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  TypingPayload.startTypingPayload(builder);
  TypingPayload.addChatId(builder, chatId);
  TypingPayload.addUserId(builder, userId);
  TypingPayload.addName(builder, nameOffset);
  return TypingPayload.endTypingPayload(builder);
}
}
