-- Convert all SERIAL primary keys to BIGINT for Snowflake IDs

ALTER TABLE verification_codes ALTER COLUMN id TYPE BIGINT;
ALTER TABLE sessions ALTER COLUMN id TYPE BIGINT;

ALTER TABLE users ALTER COLUMN id TYPE BIGINT;
ALTER TABLE contacts ALTER COLUMN id TYPE BIGINT;
ALTER TABLE blocked_users ALTER COLUMN id TYPE BIGINT;

ALTER TABLE chats ALTER COLUMN id TYPE BIGINT;
ALTER TABLE chat_members ALTER COLUMN id TYPE BIGINT;
ALTER TABLE messages ALTER COLUMN id TYPE BIGINT;
ALTER TABLE message_reads ALTER COLUMN id TYPE BIGINT;

ALTER TABLE calls ALTER COLUMN id TYPE BIGINT;

ALTER TABLE posts ALTER COLUMN id TYPE BIGINT;
ALTER TABLE post_likes ALTER COLUMN id TYPE BIGINT;
ALTER TABLE post_comments ALTER COLUMN id TYPE BIGINT;
ALTER TABLE post_views ALTER COLUMN id TYPE BIGINT;

ALTER TABLE videos ALTER COLUMN id TYPE BIGINT;
ALTER TABLE video_likes ALTER COLUMN id TYPE BIGINT;
ALTER TABLE video_comments ALTER COLUMN id TYPE BIGINT;

ALTER TABLE lives ALTER COLUMN id TYPE BIGINT;

ALTER TABLE channels ALTER COLUMN id TYPE BIGINT;
ALTER TABLE channel_subscribers ALTER COLUMN id TYPE BIGINT;
ALTER TABLE channel_posts ALTER COLUMN id TYPE BIGINT;

ALTER TABLE communities ALTER COLUMN id TYPE BIGINT;
ALTER TABLE community_members ALTER COLUMN id TYPE BIGINT;

ALTER TABLE polls ALTER COLUMN id TYPE BIGINT;
ALTER TABLE poll_options ALTER COLUMN id TYPE BIGINT;
ALTER TABLE poll_votes ALTER COLUMN id TYPE BIGINT;

ALTER TABLE products ALTER COLUMN id TYPE BIGINT;
ALTER TABLE orders ALTER COLUMN id TYPE BIGINT;
ALTER TABLE wishlists ALTER COLUMN id TYPE BIGINT;
ALTER TABLE wishlist_items ALTER COLUMN id TYPE BIGINT;
ALTER TABLE flash_deals ALTER COLUMN id TYPE BIGINT;

ALTER TABLE memes ALTER COLUMN id TYPE BIGINT;
ALTER TABLE meme_likes ALTER COLUMN id TYPE BIGINT;

ALTER TABLE sticker_packs ALTER COLUMN id TYPE BIGINT;
ALTER TABLE stickers ALTER COLUMN id TYPE BIGINT;
ALTER TABLE sticker_purchases ALTER COLUMN id TYPE BIGINT;

ALTER TABLE avatar_3d ALTER COLUMN id TYPE BIGINT;

ALTER TABLE vibe_balance ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE focus_sessions ALTER COLUMN id TYPE BIGINT;
ALTER TABLE smart_notifications ALTER COLUMN id TYPE BIGINT;

ALTER TABLE shared_notes ALTER COLUMN id TYPE BIGINT;
ALTER TABLE group_tasks ALTER COLUMN id TYPE BIGINT;

ALTER TABLE watch_sessions ALTER COLUMN id TYPE BIGINT;
ALTER TABLE game_sessions ALTER COLUMN id TYPE BIGINT;

ALTER TABLE active_calls ALTER COLUMN id TYPE BIGINT;
ALTER TABLE broadcasts ALTER COLUMN id TYPE BIGINT;
ALTER TABLE broadcast_viewers ALTER COLUMN id TYPE BIGINT;

-- Also fix FK columns that reference users/chats/etc
ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE chats ALTER COLUMN id DROP DEFAULT;
ALTER TABLE messages ALTER COLUMN id DROP DEFAULT;

-- Convert all FK _id columns from INTEGER to BIGINT to match Snowflake IDs
-- (These were missed in the initial migration)
ALTER TABLE sessions ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE contacts ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE contacts ALTER COLUMN contact_user_id TYPE BIGINT;
ALTER TABLE blocked_users ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE blocked_users ALTER COLUMN blocked_user_id TYPE BIGINT;
ALTER TABLE chat_members ALTER COLUMN chat_id TYPE BIGINT;
ALTER TABLE chat_members ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE messages ALTER COLUMN chat_id TYPE BIGINT;
ALTER TABLE messages ALTER COLUMN sender_id TYPE BIGINT;
ALTER TABLE messages ALTER COLUMN reply_to_id TYPE BIGINT;
ALTER TABLE message_reads ALTER COLUMN message_id TYPE BIGINT;
ALTER TABLE message_reads ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE calls ALTER COLUMN caller_id TYPE BIGINT;
ALTER TABLE calls ALTER COLUMN callee_id TYPE BIGINT;
ALTER TABLE posts ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE post_likes ALTER COLUMN post_id TYPE BIGINT;
ALTER TABLE post_likes ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE post_comments ALTER COLUMN post_id TYPE BIGINT;
ALTER TABLE post_comments ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE post_views ALTER COLUMN post_id TYPE BIGINT;
ALTER TABLE post_views ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE videos ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE video_likes ALTER COLUMN video_id TYPE BIGINT;
ALTER TABLE video_likes ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE video_comments ALTER COLUMN video_id TYPE BIGINT;
ALTER TABLE video_comments ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE lives ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE channels ALTER COLUMN owner_id TYPE BIGINT;
ALTER TABLE channel_subscribers ALTER COLUMN channel_id TYPE BIGINT;
ALTER TABLE channel_subscribers ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE channel_posts ALTER COLUMN channel_id TYPE BIGINT;
ALTER TABLE channel_posts ALTER COLUMN sender_id TYPE BIGINT;
ALTER TABLE communities ALTER COLUMN owner_id TYPE BIGINT;
ALTER TABLE community_members ALTER COLUMN community_id TYPE BIGINT;
ALTER TABLE community_members ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE polls ALTER COLUMN chat_id TYPE BIGINT;
ALTER TABLE polls ALTER COLUMN creator_id TYPE BIGINT;
ALTER TABLE poll_options ALTER COLUMN poll_id TYPE BIGINT;
ALTER TABLE poll_votes ALTER COLUMN poll_id TYPE BIGINT;
ALTER TABLE poll_votes ALTER COLUMN option_id TYPE BIGINT;
ALTER TABLE poll_votes ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE products ALTER COLUMN seller_id TYPE BIGINT;
ALTER TABLE orders ALTER COLUMN buyer_id TYPE BIGINT;
ALTER TABLE orders ALTER COLUMN product_id TYPE BIGINT;
ALTER TABLE wishlists ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE wishlist_items ALTER COLUMN wishlist_id TYPE BIGINT;
ALTER TABLE wishlist_items ALTER COLUMN product_id TYPE BIGINT;
ALTER TABLE flash_deals ALTER COLUMN product_id TYPE BIGINT;
ALTER TABLE memes ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE meme_likes ALTER COLUMN meme_id TYPE BIGINT;
ALTER TABLE meme_likes ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE sticker_packs ALTER COLUMN author_id TYPE BIGINT;
ALTER TABLE stickers ALTER COLUMN pack_id TYPE BIGINT;
ALTER TABLE sticker_purchases ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE sticker_purchases ALTER COLUMN pack_id TYPE BIGINT;
ALTER TABLE avatar_3d ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE focus_sessions ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE smart_notifications ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE shared_notes ALTER COLUMN chat_id TYPE BIGINT;
ALTER TABLE group_tasks ALTER COLUMN chat_id TYPE BIGINT;
ALTER TABLE watch_sessions ALTER COLUMN chat_id TYPE BIGINT;
ALTER TABLE watch_sessions ALTER COLUMN creator_id TYPE BIGINT;
ALTER TABLE game_sessions ALTER COLUMN chat_id TYPE BIGINT;
ALTER TABLE game_sessions ALTER COLUMN creator_id TYPE BIGINT;
ALTER TABLE game_sessions ALTER COLUMN game_id TYPE BIGINT;
ALTER TABLE game_sessions ALTER COLUMN winner_id TYPE BIGINT;
ALTER TABLE game_players ALTER COLUMN session_id TYPE BIGINT;
ALTER TABLE game_players ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE active_calls ALTER COLUMN caller_id TYPE BIGINT;
ALTER TABLE active_calls ALTER COLUMN callee_id TYPE BIGINT;
ALTER TABLE broadcasts ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE broadcast_viewers ALTER COLUMN broadcast_id TYPE BIGINT;
ALTER TABLE broadcast_viewers ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE two_step_settings ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE privacy_settings ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE user_stickers ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE user_stickers ALTER COLUMN sticker_id TYPE BIGINT;
ALTER TABLE voice_transcripts ALTER COLUMN message_id TYPE BIGINT;
ALTER TABLE community_groups ALTER COLUMN community_id TYPE BIGINT;
ALTER TABLE community_groups ALTER COLUMN chat_id TYPE BIGINT;
ALTER TABLE live_products ALTER COLUMN live_id TYPE BIGINT;
ALTER TABLE live_products ALTER COLUMN product_id TYPE BIGINT;
ALTER TABLE affiliate_links ALTER COLUMN creator_id TYPE BIGINT;
ALTER TABLE affiliate_links ALTER COLUMN product_id TYPE BIGINT;
ALTER TABLE avatar_customizations ALTER COLUMN user_id TYPE BIGINT;
