-- Fix id columns to use GENERATED BY DEFAULT AS IDENTITY
-- Safe for both migration path (001_init.sql → ...) and fresh DB (000_full.sql)
-- Skips tables that already have identity or sequence default

DO $$
DECLARE
  rec RECORD;
  has_default BOOLEAN;
BEGIN
  FOR rec IN (
    SELECT table_schema, table_name
    FROM information_schema.columns
    WHERE column_name = 'id'
      AND is_identity = 'NO'
      AND table_schema = 'public'
      AND table_name NOT LIKE 'pg_%'
  ) LOOP
    -- Check if column already has a default value (e.g. from SERIAL → BIGINT migration)
    EXECUTE format('
      SELECT EXISTS (
        SELECT 1 FROM pg_attrdef
        WHERE adrelid = %L::regclass
          AND adnum = (SELECT attnum FROM pg_attribute WHERE attrelid = %L::regclass AND attname = ''id'')
      )', rec.table_name, rec.table_name) INTO has_default;

    IF NOT has_default THEN
      BEGIN
        EXECUTE format('ALTER TABLE %I.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', rec.table_schema, rec.table_name);
        RAISE NOTICE 'Added identity to %.%', rec.table_schema, rec.table_name;
      EXCEPTION WHEN OTHERS THEN
        RAISE WARNING 'Could not add identity to %.%: %', rec.table_schema, rec.table_name, SQLERRM;
      END;
    ELSE
      RAISE NOTICE 'Skipping %.% (already has default)', rec.table_schema, rec.table_name;
    END IF;
  END LOOP;
END $$;
