// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class RestoreSessionRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RestoreSessionRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRestoreSessionRequest(bb:flatbuffers.ByteBuffer, obj?:RestoreSessionRequest):RestoreSessionRequest {
  return (obj || new RestoreSessionRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRestoreSessionRequest(bb:flatbuffers.ByteBuffer, obj?:RestoreSessionRequest):RestoreSessionRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RestoreSessionRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

token():string|null
token(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
token(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startRestoreSessionRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addToken(builder:flatbuffers.Builder, tokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tokenOffset, 0);
}

static endRestoreSessionRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // token
  return offset;
}

static createRestoreSessionRequest(builder:flatbuffers.Builder, tokenOffset:flatbuffers.Offset):flatbuffers.Offset {
  RestoreSessionRequest.startRestoreSessionRequest(builder);
  RestoreSessionRequest.addToken(builder, tokenOffset);
  return RestoreSessionRequest.endRestoreSessionRequest(builder);
}
}
