// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SendCodeRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SendCodeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSendCodeRequest(bb:flatbuffers.ByteBuffer, obj?:SendCodeRequest):SendCodeRequest {
  return (obj || new SendCodeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSendCodeRequest(bb:flatbuffers.ByteBuffer, obj?:SendCodeRequest):SendCodeRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SendCodeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

phone():string|null
phone(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
phone(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSendCodeRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPhone(builder:flatbuffers.Builder, phoneOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, phoneOffset, 0);
}

static endSendCodeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // phone
  return offset;
}

static createSendCodeRequest(builder:flatbuffers.Builder, phoneOffset:flatbuffers.Offset):flatbuffers.Offset {
  SendCodeRequest.startSendCodeRequest(builder);
  SendCodeRequest.addPhone(builder, phoneOffset);
  return SendCodeRequest.endSendCodeRequest(builder);
}
}
