// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class VerifyCodeResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VerifyCodeResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVerifyCodeResponse(bb:flatbuffers.ByteBuffer, obj?:VerifyCodeResponse):VerifyCodeResponse {
  return (obj || new VerifyCodeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVerifyCodeResponse(bb:flatbuffers.ByteBuffer, obj?:VerifyCodeResponse):VerifyCodeResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VerifyCodeResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ok():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

token():string|null
token(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
token(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

userId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

displayName():string|null
displayName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
displayName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

avatar():string|null
avatar(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
avatar(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isNew():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

error():string|null
error(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
error(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startVerifyCodeResponse(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addOk(builder:flatbuffers.Builder, ok:boolean) {
  builder.addFieldInt8(0, +ok, +false);
}

static addToken(builder:flatbuffers.Builder, tokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, tokenOffset, 0);
}

static addUserId(builder:flatbuffers.Builder, userId:bigint) {
  builder.addFieldInt64(2, userId, BigInt('0'));
}

static addDisplayName(builder:flatbuffers.Builder, displayNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, displayNameOffset, 0);
}

static addAvatar(builder:flatbuffers.Builder, avatarOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, avatarOffset, 0);
}

static addIsNew(builder:flatbuffers.Builder, isNew:boolean) {
  builder.addFieldInt8(5, +isNew, +false);
}

static addError(builder:flatbuffers.Builder, errorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, errorOffset, 0);
}

static endVerifyCodeResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVerifyCodeResponse(builder:flatbuffers.Builder, ok:boolean, tokenOffset:flatbuffers.Offset, userId:bigint, displayNameOffset:flatbuffers.Offset, avatarOffset:flatbuffers.Offset, isNew:boolean, errorOffset:flatbuffers.Offset):flatbuffers.Offset {
  VerifyCodeResponse.startVerifyCodeResponse(builder);
  VerifyCodeResponse.addOk(builder, ok);
  VerifyCodeResponse.addToken(builder, tokenOffset);
  VerifyCodeResponse.addUserId(builder, userId);
  VerifyCodeResponse.addDisplayName(builder, displayNameOffset);
  VerifyCodeResponse.addAvatar(builder, avatarOffset);
  VerifyCodeResponse.addIsNew(builder, isNew);
  VerifyCodeResponse.addError(builder, errorOffset);
  return VerifyCodeResponse.endVerifyCodeResponse(builder);
}
}
