ALTER TABLE vibe_balance ADD COLUMN IF NOT EXISTS stars INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS live_gifts (
  id BIGINT PRIMARY KEY,
  live_id BIGINT NOT NULL REFERENCES lives(id),
  sender_id BIGINT NOT NULL REFERENCES users(id),
  recipient_id BIGINT NOT NULL REFERENCES users(id),
  stars INTEGER NOT NULL DEFAULT 1,
  message TEXT DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
