// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StatusPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StatusPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStatusPayload(bb:flatbuffers.ByteBuffer, obj?:StatusPayload):StatusPayload {
  return (obj || new StatusPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStatusPayload(bb:flatbuffers.ByteBuffer, obj?:StatusPayload):StatusPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StatusPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

userId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

online():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startStatusPayload(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addUserId(builder:flatbuffers.Builder, userId:bigint) {
  builder.addFieldInt64(0, userId, BigInt('0'));
}

static addOnline(builder:flatbuffers.Builder, online:boolean) {
  builder.addFieldInt8(1, +online, +false);
}

static endStatusPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStatusPayload(builder:flatbuffers.Builder, userId:bigint, online:boolean):flatbuffers.Offset {
  StatusPayload.startStatusPayload(builder);
  StatusPayload.addUserId(builder, userId);
  StatusPayload.addOnline(builder, online);
  return StatusPayload.endStatusPayload(builder);
}
}
