// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Auth

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RestoreSessionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRestoreSessionRequest(buf []byte, offset flatbuffers.UOffsetT) *RestoreSessionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RestoreSessionRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishRestoreSessionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRestoreSessionRequest(buf []byte, offset flatbuffers.UOffsetT) *RestoreSessionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RestoreSessionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRestoreSessionRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RestoreSessionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RestoreSessionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RestoreSessionRequest) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RestoreSessionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RestoreSessionRequestAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func RestoreSessionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
