// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Auth

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RestoreSessionResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsRestoreSessionResponse(buf []byte, offset flatbuffers.UOffsetT) *RestoreSessionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RestoreSessionResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishRestoreSessionResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRestoreSessionResponse(buf []byte, offset flatbuffers.UOffsetT) *RestoreSessionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RestoreSessionResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRestoreSessionResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RestoreSessionResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RestoreSessionResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RestoreSessionResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *RestoreSessionResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *RestoreSessionResponse) UserId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RestoreSessionResponse) MutateUserId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *RestoreSessionResponse) DisplayName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RestoreSessionResponse) Phone() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RestoreSessionResponse) Avatar() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RestoreSessionResponse) Bio() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RestoreSessionResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func RestoreSessionResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func RestoreSessionResponseAddUserId(builder *flatbuffers.Builder, userId uint64) {
	builder.PrependUint64Slot(1, userId, 0)
}
func RestoreSessionResponseAddDisplayName(builder *flatbuffers.Builder, displayName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(displayName), 0)
}
func RestoreSessionResponseAddPhone(builder *flatbuffers.Builder, phone flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(phone), 0)
}
func RestoreSessionResponseAddAvatar(builder *flatbuffers.Builder, avatar flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(avatar), 0)
}
func RestoreSessionResponseAddBio(builder *flatbuffers.Builder, bio flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(bio), 0)
}
func RestoreSessionResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
