// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Auth

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SendCodeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSendCodeRequest(buf []byte, offset flatbuffers.UOffsetT) *SendCodeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SendCodeRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSendCodeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSendCodeRequest(buf []byte, offset flatbuffers.UOffsetT) *SendCodeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SendCodeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSendCodeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SendCodeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SendCodeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SendCodeRequest) Phone() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SendCodeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SendCodeRequestAddPhone(builder *flatbuffers.Builder, phone flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(phone), 0)
}
func SendCodeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
