// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Call {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Call {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCall(bb:flatbuffers.ByteBuffer, obj?:Call):Call {
  return (obj || new Call()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCall(bb:flatbuffers.ByteBuffer, obj?:Call):Call {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Call()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

callerId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

calleeId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

callType():string|null
callType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
callType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

status():string|null
status(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
status(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

duration():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

createdAt():string|null
createdAt(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
createdAt(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

direction():string|null
direction(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
direction(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

otherId():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

otherName():string|null
otherName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
otherName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

otherAvatar():string|null
otherAvatar(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
otherAvatar(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startCall(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addCallerId(builder:flatbuffers.Builder, callerId:number) {
  builder.addFieldInt32(1, callerId, 0);
}

static addCalleeId(builder:flatbuffers.Builder, calleeId:number) {
  builder.addFieldInt32(2, calleeId, 0);
}

static addCallType(builder:flatbuffers.Builder, callTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, callTypeOffset, 0);
}

static addStatus(builder:flatbuffers.Builder, statusOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, statusOffset, 0);
}

static addDuration(builder:flatbuffers.Builder, duration:number) {
  builder.addFieldInt32(5, duration, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAtOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, createdAtOffset, 0);
}

static addDirection(builder:flatbuffers.Builder, directionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, directionOffset, 0);
}

static addOtherId(builder:flatbuffers.Builder, otherId:number) {
  builder.addFieldInt32(8, otherId, 0);
}

static addOtherName(builder:flatbuffers.Builder, otherNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, otherNameOffset, 0);
}

static addOtherAvatar(builder:flatbuffers.Builder, otherAvatarOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, otherAvatarOffset, 0);
}

static endCall(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCall(builder:flatbuffers.Builder, id:number, callerId:number, calleeId:number, callTypeOffset:flatbuffers.Offset, statusOffset:flatbuffers.Offset, duration:number, createdAtOffset:flatbuffers.Offset, directionOffset:flatbuffers.Offset, otherId:number, otherNameOffset:flatbuffers.Offset, otherAvatarOffset:flatbuffers.Offset):flatbuffers.Offset {
  Call.startCall(builder);
  Call.addId(builder, id);
  Call.addCallerId(builder, callerId);
  Call.addCalleeId(builder, calleeId);
  Call.addCallType(builder, callTypeOffset);
  Call.addStatus(builder, statusOffset);
  Call.addDuration(builder, duration);
  Call.addCreatedAt(builder, createdAtOffset);
  Call.addDirection(builder, directionOffset);
  Call.addOtherId(builder, otherId);
  Call.addOtherName(builder, otherNameOffset);
  Call.addOtherAvatar(builder, otherAvatarOffset);
  return Call.endCall(builder);
}
}
