// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Chat {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Chat {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChat(bb:flatbuffers.ByteBuffer, obj?:Chat):Chat {
  return (obj || new Chat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChat(bb:flatbuffers.ByteBuffer, obj?:Chat):Chat {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Chat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

chatType():string|null
chatType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
chatType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

avatar():string|null
avatar(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
avatar(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

lastMessage():string|null
lastMessage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
lastMessage(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

lastMessageTime():string|null
lastMessageTime(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
lastMessageTime(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

lastSenderId():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

createdAt():string|null
createdAt(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
createdAt(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

unread():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

pinned():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startChat(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addChatType(builder:flatbuffers.Builder, chatTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, chatTypeOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addAvatar(builder:flatbuffers.Builder, avatarOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, avatarOffset, 0);
}

static addLastMessage(builder:flatbuffers.Builder, lastMessageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, lastMessageOffset, 0);
}

static addLastMessageTime(builder:flatbuffers.Builder, lastMessageTimeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, lastMessageTimeOffset, 0);
}

static addLastSenderId(builder:flatbuffers.Builder, lastSenderId:number) {
  builder.addFieldInt32(6, lastSenderId, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAtOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, createdAtOffset, 0);
}

static addUnread(builder:flatbuffers.Builder, unread:number) {
  builder.addFieldInt32(8, unread, 0);
}

static addPinned(builder:flatbuffers.Builder, pinned:boolean) {
  builder.addFieldInt8(9, +pinned, +false);
}

static endChat(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChat(builder:flatbuffers.Builder, id:number, chatTypeOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, avatarOffset:flatbuffers.Offset, lastMessageOffset:flatbuffers.Offset, lastMessageTimeOffset:flatbuffers.Offset, lastSenderId:number, createdAtOffset:flatbuffers.Offset, unread:number, pinned:boolean):flatbuffers.Offset {
  Chat.startChat(builder);
  Chat.addId(builder, id);
  Chat.addChatType(builder, chatTypeOffset);
  Chat.addName(builder, nameOffset);
  Chat.addAvatar(builder, avatarOffset);
  Chat.addLastMessage(builder, lastMessageOffset);
  Chat.addLastMessageTime(builder, lastMessageTimeOffset);
  Chat.addLastSenderId(builder, lastSenderId);
  Chat.addCreatedAt(builder, createdAtOffset);
  Chat.addUnread(builder, unread);
  Chat.addPinned(builder, pinned);
  return Chat.endChat(builder);
}
}
