// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Post {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Post {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPost(bb:flatbuffers.ByteBuffer, obj?:Post):Post {
  return (obj || new Post()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPost(bb:flatbuffers.ByteBuffer, obj?:Post):Post {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Post()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

userId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

media():string|null
media(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
media(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mediaType():string|null
mediaType(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mediaType(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

likesCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

commentsCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

createdAt():string|null
createdAt(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
createdAt(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

expiresAt():string|null
expiresAt(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
expiresAt(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

displayName():string|null
displayName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
displayName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

avatar():string|null
avatar(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
avatar(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

views():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startPost(builder:flatbuffers.Builder) {
  builder.startObject(12);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addUserId(builder:flatbuffers.Builder, userId:number) {
  builder.addFieldInt32(1, userId, 0);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, textOffset, 0);
}

static addMedia(builder:flatbuffers.Builder, mediaOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, mediaOffset, 0);
}

static addMediaType(builder:flatbuffers.Builder, mediaTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, mediaTypeOffset, 0);
}

static addLikesCount(builder:flatbuffers.Builder, likesCount:number) {
  builder.addFieldInt32(5, likesCount, 0);
}

static addCommentsCount(builder:flatbuffers.Builder, commentsCount:number) {
  builder.addFieldInt32(6, commentsCount, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAtOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, createdAtOffset, 0);
}

static addExpiresAt(builder:flatbuffers.Builder, expiresAtOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, expiresAtOffset, 0);
}

static addDisplayName(builder:flatbuffers.Builder, displayNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, displayNameOffset, 0);
}

static addAvatar(builder:flatbuffers.Builder, avatarOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, avatarOffset, 0);
}

static addViews(builder:flatbuffers.Builder, views:bigint) {
  builder.addFieldInt64(11, views, BigInt('0'));
}

static endPost(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPost(builder:flatbuffers.Builder, id:number, userId:number, textOffset:flatbuffers.Offset, mediaOffset:flatbuffers.Offset, mediaTypeOffset:flatbuffers.Offset, likesCount:number, commentsCount:number, createdAtOffset:flatbuffers.Offset, expiresAtOffset:flatbuffers.Offset, displayNameOffset:flatbuffers.Offset, avatarOffset:flatbuffers.Offset, views:bigint):flatbuffers.Offset {
  Post.startPost(builder);
  Post.addId(builder, id);
  Post.addUserId(builder, userId);
  Post.addText(builder, textOffset);
  Post.addMedia(builder, mediaOffset);
  Post.addMediaType(builder, mediaTypeOffset);
  Post.addLikesCount(builder, likesCount);
  Post.addCommentsCount(builder, commentsCount);
  Post.addCreatedAt(builder, createdAtOffset);
  Post.addExpiresAt(builder, expiresAtOffset);
  Post.addDisplayName(builder, displayNameOffset);
  Post.addAvatar(builder, avatarOffset);
  Post.addViews(builder, views);
  return Post.endPost(builder);
}
}
