// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Session {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Session {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSession(bb:flatbuffers.ByteBuffer, obj?:Session):Session {
  return (obj || new Session()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSession(bb:flatbuffers.ByteBuffer, obj?:Session):Session {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Session()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

deviceName():string|null
deviceName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
deviceName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

deviceId():string|null
deviceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
deviceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

createdAt():string|null
createdAt(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
createdAt(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

lastActive():string|null
lastActive(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
lastActive(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startSession(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addDeviceName(builder:flatbuffers.Builder, deviceNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, deviceNameOffset, 0);
}

static addDeviceId(builder:flatbuffers.Builder, deviceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, deviceIdOffset, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAtOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, createdAtOffset, 0);
}

static addLastActive(builder:flatbuffers.Builder, lastActiveOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, lastActiveOffset, 0);
}

static endSession(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSession(builder:flatbuffers.Builder, id:number, deviceNameOffset:flatbuffers.Offset, deviceIdOffset:flatbuffers.Offset, createdAtOffset:flatbuffers.Offset, lastActiveOffset:flatbuffers.Offset):flatbuffers.Offset {
  Session.startSession(builder);
  Session.addId(builder, id);
  Session.addDeviceName(builder, deviceNameOffset);
  Session.addDeviceId(builder, deviceIdOffset);
  Session.addCreatedAt(builder, createdAtOffset);
  Session.addLastActive(builder, lastActiveOffset);
  return Session.endSession(builder);
}
}
