// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Video {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Video {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVideo(bb:flatbuffers.ByteBuffer, obj?:Video):Video {
  return (obj || new Video()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVideo(bb:flatbuffers.ByteBuffer, obj?:Video):Video {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Video()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

userId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

videoUrl():string|null
videoUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
videoUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

thumbnail():string|null
thumbnail(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
thumbnail(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

caption():string|null
caption(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
caption(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

likesCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

commentsCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

createdAt():string|null
createdAt(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
createdAt(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

displayName():string|null
displayName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
displayName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

avatar():string|null
avatar(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
avatar(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

username():string|null
username(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
username(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startVideo(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addUserId(builder:flatbuffers.Builder, userId:number) {
  builder.addFieldInt32(1, userId, 0);
}

static addVideoUrl(builder:flatbuffers.Builder, videoUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, videoUrlOffset, 0);
}

static addThumbnail(builder:flatbuffers.Builder, thumbnailOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, thumbnailOffset, 0);
}

static addCaption(builder:flatbuffers.Builder, captionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, captionOffset, 0);
}

static addLikesCount(builder:flatbuffers.Builder, likesCount:number) {
  builder.addFieldInt32(5, likesCount, 0);
}

static addCommentsCount(builder:flatbuffers.Builder, commentsCount:number) {
  builder.addFieldInt32(6, commentsCount, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAtOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, createdAtOffset, 0);
}

static addDisplayName(builder:flatbuffers.Builder, displayNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, displayNameOffset, 0);
}

static addAvatar(builder:flatbuffers.Builder, avatarOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, avatarOffset, 0);
}

static addUsername(builder:flatbuffers.Builder, usernameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, usernameOffset, 0);
}

static endVideo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVideo(builder:flatbuffers.Builder, id:number, userId:number, videoUrlOffset:flatbuffers.Offset, thumbnailOffset:flatbuffers.Offset, captionOffset:flatbuffers.Offset, likesCount:number, commentsCount:number, createdAtOffset:flatbuffers.Offset, displayNameOffset:flatbuffers.Offset, avatarOffset:flatbuffers.Offset, usernameOffset:flatbuffers.Offset):flatbuffers.Offset {
  Video.startVideo(builder);
  Video.addId(builder, id);
  Video.addUserId(builder, userId);
  Video.addVideoUrl(builder, videoUrlOffset);
  Video.addThumbnail(builder, thumbnailOffset);
  Video.addCaption(builder, captionOffset);
  Video.addLikesCount(builder, likesCount);
  Video.addCommentsCount(builder, commentsCount);
  Video.addCreatedAt(builder, createdAtOffset);
  Video.addDisplayName(builder, displayNameOffset);
  Video.addAvatar(builder, avatarOffset);
  Video.addUsername(builder, usernameOffset);
  return Video.endVideo(builder);
}
}
