// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class VideoComment {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VideoComment {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVideoComment(bb:flatbuffers.ByteBuffer, obj?:VideoComment):VideoComment {
  return (obj || new VideoComment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVideoComment(bb:flatbuffers.ByteBuffer, obj?:VideoComment):VideoComment {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VideoComment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

videoId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

userId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

createdAt():string|null
createdAt(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
createdAt(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

displayName():string|null
displayName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
displayName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

avatar():string|null
avatar(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
avatar(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

username():string|null
username(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
username(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startVideoComment(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
}

static addVideoId(builder:flatbuffers.Builder, videoId:number) {
  builder.addFieldInt32(1, videoId, 0);
}

static addUserId(builder:flatbuffers.Builder, userId:number) {
  builder.addFieldInt32(2, userId, 0);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, textOffset, 0);
}

static addCreatedAt(builder:flatbuffers.Builder, createdAtOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, createdAtOffset, 0);
}

static addDisplayName(builder:flatbuffers.Builder, displayNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, displayNameOffset, 0);
}

static addAvatar(builder:flatbuffers.Builder, avatarOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, avatarOffset, 0);
}

static addUsername(builder:flatbuffers.Builder, usernameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, usernameOffset, 0);
}

static endVideoComment(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVideoComment(builder:flatbuffers.Builder, id:number, videoId:number, userId:number, textOffset:flatbuffers.Offset, createdAtOffset:flatbuffers.Offset, displayNameOffset:flatbuffers.Offset, avatarOffset:flatbuffers.Offset, usernameOffset:flatbuffers.Offset):flatbuffers.Offset {
  VideoComment.startVideoComment(builder);
  VideoComment.addId(builder, id);
  VideoComment.addVideoId(builder, videoId);
  VideoComment.addUserId(builder, userId);
  VideoComment.addText(builder, textOffset);
  VideoComment.addCreatedAt(builder, createdAtOffset);
  VideoComment.addDisplayName(builder, displayNameOffset);
  VideoComment.addAvatar(builder, avatarOffset);
  VideoComment.addUsername(builder, usernameOffset);
  return VideoComment.endVideoComment(builder);
}
}
