// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Media

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UploadChunkResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsUploadChunkResponse(buf []byte, offset flatbuffers.UOffsetT) *UploadChunkResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UploadChunkResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishUploadChunkResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUploadChunkResponse(buf []byte, offset flatbuffers.UOffsetT) *UploadChunkResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UploadChunkResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUploadChunkResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UploadChunkResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UploadChunkResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UploadChunkResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *UploadChunkResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *UploadChunkResponse) Received() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UploadChunkResponse) MutateReceived(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *UploadChunkResponse) Total() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UploadChunkResponse) MutateTotal(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *UploadChunkResponse) Url() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UploadChunkResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UploadChunkResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func UploadChunkResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func UploadChunkResponseAddReceived(builder *flatbuffers.Builder, received uint32) {
	builder.PrependUint32Slot(1, received, 0)
}
func UploadChunkResponseAddTotal(builder *flatbuffers.Builder, total uint32) {
	builder.PrependUint32Slot(2, total, 0)
}
func UploadChunkResponseAddUrl(builder *flatbuffers.Builder, url flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(url), 0)
}
func UploadChunkResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(error), 0)
}
func UploadChunkResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
