// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Media

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UploadStartResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsUploadStartResponse(buf []byte, offset flatbuffers.UOffsetT) *UploadStartResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UploadStartResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishUploadStartResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUploadStartResponse(buf []byte, offset flatbuffers.UOffsetT) *UploadStartResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UploadStartResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUploadStartResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UploadStartResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UploadStartResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UploadStartResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *UploadStartResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *UploadStartResponse) UploadId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UploadStartResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UploadStartResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UploadStartResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func UploadStartResponseAddUploadId(builder *flatbuffers.Builder, uploadId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(uploadId), 0)
}
func UploadStartResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(error), 0)
}
func UploadStartResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
