// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Media

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UploadStartRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUploadStartRequest(buf []byte, offset flatbuffers.UOffsetT) *UploadStartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UploadStartRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishUploadStartRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUploadStartRequest(buf []byte, offset flatbuffers.UOffsetT) *UploadStartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UploadStartRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUploadStartRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UploadStartRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UploadStartRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UploadStartRequest) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UploadStartRequest) Mime() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UploadStartRequest) Size() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UploadStartRequest) MutateSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *UploadStartRequest) TotalChunks() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UploadStartRequest) MutateTotalChunks(n uint16) bool {
	return rcv._tab.MutateUint16Slot(10, n)
}

func UploadStartRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func UploadStartRequestAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func UploadStartRequestAddMime(builder *flatbuffers.Builder, mime flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(mime), 0)
}
func UploadStartRequestAddSize(builder *flatbuffers.Builder, size uint32) {
	builder.PrependUint32Slot(2, size, 0)
}
func UploadStartRequestAddTotalChunks(builder *flatbuffers.Builder, totalChunks uint16) {
	builder.PrependUint16Slot(3, totalChunks, 0)
}
func UploadStartRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
