// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Media

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UploadChunkRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUploadChunkRequest(buf []byte, offset flatbuffers.UOffsetT) *UploadChunkRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UploadChunkRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishUploadChunkRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUploadChunkRequest(buf []byte, offset flatbuffers.UOffsetT) *UploadChunkRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UploadChunkRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUploadChunkRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UploadChunkRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UploadChunkRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UploadChunkRequest) UploadId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UploadChunkRequest) Index() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UploadChunkRequest) MutateIndex(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func (rcv *UploadChunkRequest) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *UploadChunkRequest) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *UploadChunkRequest) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *UploadChunkRequest) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func UploadChunkRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func UploadChunkRequestAddUploadId(builder *flatbuffers.Builder, uploadId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(uploadId), 0)
}
func UploadChunkRequestAddIndex(builder *flatbuffers.Builder, index uint16) {
	builder.PrependUint16Slot(1, index, 0)
}
func UploadChunkRequestAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(data), 0)
}
func UploadChunkRequestStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func UploadChunkRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
