// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Media

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UploadCancelRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUploadCancelRequest(buf []byte, offset flatbuffers.UOffsetT) *UploadCancelRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UploadCancelRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishUploadCancelRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUploadCancelRequest(buf []byte, offset flatbuffers.UOffsetT) *UploadCancelRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UploadCancelRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUploadCancelRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UploadCancelRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UploadCancelRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UploadCancelRequest) UploadId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UploadCancelRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UploadCancelRequestAddUploadId(builder *flatbuffers.Builder, uploadId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(uploadId), 0)
}
func UploadCancelRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
