export interface Country {
  code: string;
  name: string;
  dial: string;
  flag: string;
  length: number;
}

export const countries: Country[] = [
  { code: 'BO', name: 'Bolivia', dial: '591', flag: '🇧🇴', length: 8 },
  { code: 'MX', name: 'México', dial: '52', flag: '🇲🇽', length: 10 },
  { code: 'US', name: 'Estados Unidos', dial: '1', flag: '🇺🇸', length: 10 },
  { code: 'ES', name: 'España', dial: '34', flag: '🇪🇸', length: 9 },
  { code: 'AR', name: 'Argentina', dial: '54', flag: '🇦🇷', length: 10 },
  { code: 'CO', name: 'Colombia', dial: '57', flag: '🇨🇴', length: 10 },
  { code: 'CL', name: 'Chile', dial: '56', flag: '🇨🇱', length: 9 },
  { code: 'PE', name: 'Perú', dial: '51', flag: '🇵🇪', length: 9 },
  { code: 'VE', name: 'Venezuela', dial: '58', flag: '🇻🇪', length: 10 },
  { code: 'EC', name: 'Ecuador', dial: '593', flag: '🇪🇨', length: 9 },
  { code: 'GT', name: 'Guatemala', dial: '502', flag: '🇬🇹', length: 8 },
  { code: 'CU', name: 'Cuba', dial: '53', flag: '🇨🇺', length: 8 },
  { code: 'DO', name: 'República Dominicana', dial: '1-809', flag: '🇩🇴', length: 10 },
  { code: 'HN', name: 'Honduras', dial: '504', flag: '🇭🇳', length: 8 },
  { code: 'PY', name: 'Paraguay', dial: '595', flag: '🇵🇾', length: 9 },
  { code: 'SV', name: 'El Salvador', dial: '503', flag: '🇸🇻', length: 8 },
  { code: 'NI', name: 'Nicaragua', dial: '505', flag: '🇳🇮', length: 8 },
  { code: 'CR', name: 'Costa Rica', dial: '506', flag: '🇨🇷', length: 8 },
  { code: 'PA', name: 'Panamá', dial: '507', flag: '🇵🇦', length: 8 },
  { code: 'UY', name: 'Uruguay', dial: '598', flag: '🇺🇾', length: 8 },
  { code: 'PR', name: 'Puerto Rico', dial: '1-787', flag: '🇵🇷', length: 10 },
  { code: 'BR', name: 'Brasil', dial: '55', flag: '🇧🇷', length: 11 },
  { code: 'GB', name: 'Reino Unido', dial: '44', flag: '🇬🇧', length: 10 },
  { code: 'FR', name: 'Francia', dial: '33', flag: '🇫🇷', length: 9 },
  { code: 'DE', name: 'Alemania', dial: '49', flag: '🇩🇪', length: 11 },
  { code: 'IT', name: 'Italia', dial: '39', flag: '🇮🇹', length: 10 },
  { code: 'PT', name: 'Portugal', dial: '351', flag: '🇵🇹', length: 9 },
  { code: 'NL', name: 'Países Bajos', dial: '31', flag: '🇳🇱', length: 9 },
  { code: 'BE', name: 'Bélgica', dial: '32', flag: '🇧🇪', length: 9 },
  { code: 'CH', name: 'Suiza', dial: '41', flag: '🇨🇭', length: 9 },
  { code: 'SE', name: 'Suecia', dial: '46', flag: '🇸🇪', length: 9 },
  { code: 'NO', name: 'Noruega', dial: '47', flag: '🇳🇴', length: 8 },
  { code: 'DK', name: 'Dinamarca', dial: '45', flag: '🇩🇰', length: 8 },
  { code: 'FI', name: 'Finlandia', dial: '358', flag: '🇫🇮', length: 9 },
  { code: 'IE', name: 'Irlanda', dial: '353', flag: '🇮🇪', length: 9 },
  { code: 'AT', name: 'Austria', dial: '43', flag: '🇦🇹', length: 10 },
  { code: 'GR', name: 'Grecia', dial: '30', flag: '🇬🇷', length: 10 },
  { code: 'PL', name: 'Polonia', dial: '48', flag: '🇵🇱', length: 9 },
  { code: 'CZ', name: 'República Checa', dial: '420', flag: '🇨🇿', length: 9 },
  { code: 'HU', name: 'Hungría', dial: '36', flag: '🇭🇺', length: 9 },
  { code: 'RO', name: 'Rumanía', dial: '40', flag: '🇷🇴', length: 9 },
  { code: 'RU', name: 'Rusia', dial: '7', flag: '🇷🇺', length: 10 },
  { code: 'UA', name: 'Ucrania', dial: '380', flag: '🇺🇦', length: 9 },
  { code: 'TR', name: 'Turquía', dial: '90', flag: '🇹🇷', length: 10 },
  { code: 'IL', name: 'Israel', dial: '972', flag: '🇮🇱', length: 9 },
  { code: 'SA', name: 'Arabia Saudita', dial: '966', flag: '🇸🇦', length: 9 },
  { code: 'AE', name: 'Emiratos Árabes', dial: '971', flag: '🇦🇪', length: 9 },
  { code: 'IN', name: 'India', dial: '91', flag: '🇮🇳', length: 10 },
  { code: 'CN', name: 'China', dial: '86', flag: '🇨🇳', length: 11 },
  { code: 'JP', name: 'Japón', dial: '81', flag: '🇯🇵', length: 10 },
  { code: 'KR', name: 'Corea del Sur', dial: '82', flag: '🇰🇷', length: 10 },
  { code: 'AU', name: 'Australia', dial: '61', flag: '🇦🇺', length: 9 },
  { code: 'NZ', name: 'Nueva Zelanda', dial: '64', flag: '🇳🇿', length: 9 },
  { code: 'ZA', name: 'Sudáfrica', dial: '27', flag: '🇿🇦', length: 9 },
  { code: 'EG', name: 'Egipto', dial: '20', flag: '🇪🇬', length: 10 },
  { code: 'MA', name: 'Marruecos', dial: '212', flag: '🇲🇦', length: 9 },
  { code: 'NG', name: 'Nigeria', dial: '234', flag: '🇳🇬', length: 11 },
  { code: 'KE', name: 'Kenia', dial: '254', flag: '🇰🇪', length: 9 },
  { code: 'PH', name: 'Filipinas', dial: '63', flag: '🇵🇭', length: 10 },
  { code: 'MY', name: 'Malasia', dial: '60', flag: '🇲🇾', length: 10 },
  { code: 'SG', name: 'Singapur', dial: '65', flag: '🇸🇬', length: 8 },
  { code: 'TH', name: 'Tailandia', dial: '66', flag: '🇹🇭', length: 9 },
  { code: 'VN', name: 'Vietnam', dial: '84', flag: '🇻🇳', length: 10 },
  { code: 'ID', name: 'Indonesia', dial: '62', flag: '🇮🇩', length: 11 },
  { code: 'PK', name: 'Pakistán', dial: '92', flag: '🇵🇰', length: 10 },
  { code: 'BD', name: 'Bangladesh', dial: '880', flag: '🇧🇩', length: 10 },
  { code: 'CA', name: 'Canadá', dial: '1', flag: '🇨🇦', length: 10 },
];

export function getDefaultCountry(): Country {
  return countries[0];
}
